### ISSUE TITLE
Creation of time series objects in memory even though it isn't used

### ISSUE THREAD

**Issue by CarsonBurke** [glitchassassin/screeps-viz#5]
![image](https://user-images.githubusercontent.com/48334001/200189917-f99b4a3e-f2db-4fc1-a2de-fc6f54affc14.png)

 I have no code utilizing the time series widget, yet the library has still implemented the time series objects into my memory. It's clutter that I'd really like to not have. 
 
 Would you like me to make a PR or are you able to reconcile this? :)

**Comment by glitchassassin** [comment]
Fixed in version 2.1.2, you should be able to remove these manually

**Comment by CarsonBurke** [comment]
Much appreciated!!
